typography_spectrum: 0.09462778363376856
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23200531536713243
  lightness: 0.8891976696904749
  saturation: 0.1716762245632708
  rhythmicContrast: 0.2992561978753656
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8646745439618826
analytics:
  google: null
  facebook: null
  twitter: null
name: givemethegoodnews
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Me
    url: alecsynnestvedt.com
    type: external
favicon: null
purpose: []
